App\Entity\Movie:
  type: entity
  repositoryClass: App\Repository\MovieRepository
  # table: movies
  # schema: schema_name # The schema the table lies in, for platforms that support schemas (Optional, >= 2.5)
  # readOnly: true
  # indexes:
    # name_index:
      # columns: [ name ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    title:
      type: string
      # length: 50
    synopsis:
      type: string
      # length: 300
      
    annee:
      type: integer
      # column: login_count
      # nullable: false
      # options:
        # unsigned: true
        # default: 0

  manyToMany:
    listMovies:
      targetEntity: ListMovie
      mappedBy: movies
      joinTable:
        name: listMovies_movies
        joinColumns:
          movie_id:
            referencedColumnName: id
        inverseJoinColumns:
          list_movie_id:
            referencedColumnName: id
  # lifecycleCallbacks:
    # prePersist: [ doStuffOnPrePersist, doOtherStuffOnPrePersistToo ]
    # postPersist: [ doStuffOnPostPersist ]
    
