App\Entity\Movie:
    exclusion_policy: ALL

    properties:

        id:
            expose: true
        title:
            expose: true
        annee:
            expose: true
        synopsis:
            expose: true